# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path('Flutter/Generated.xcconfig', __dir__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Cannot find generated Xcode build settings file. Make sure flutter pub get is executed first."
  end
  File.readlines(generated_xcode_build_settings_path).each do |line|
    matches = line.match(/FLUTTER_ROOT\s*=\s*(.*)/)
    return matches[1].strip if matches
  end
  raise 'FLUTTER_ROOT not found in Generated.xcconfig'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

post_install do |installer|
  flutter_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
